"""init usuarios

Revision ID: 3df9f44b97f9
Revises: 969dddec2b06
Create Date: 2026-07-31 17:09:17.891790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3df9f44b97f9'
down_revision: Union[str, Sequence[str], None] = '969dddec2b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fecha_registro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('fecha_registro', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
